### ISSUE TITLE
pes property in last nal units is null

### ISSUE THREAD

**Issue by ost12666** [Eyevinn/hls-ts-js#3]
When I call getNalUnits(), the last few nal units have null in the pes field. Any idea why?

**Comment by birme** [comment]
Thank you for the report.

I have no obvious idea to what could be wrong and would need to look into this a bit deeper. Any chance you can provide me with a sample file?

**Comment by ost12666** [comment]
It happens on every TS I tested, sometimes 2 nulls sometimes 4, here is one example:

https://wowzaec2demo.streamlock.net/vod-multitrack/_definst_/smil:ElephantsDream/elephantsdream2.smil/media_w1726930926_b2962000_vo_slen_t64TWFpbg==_1.ts

**Comment by birme** [comment]
Thanks, will have a look at this.

**Comment by ost12666** [comment]
any news?

**Comment by birme** [comment]
Sorry, I haven't had the chance to have a look at this yet.

**Comment by ost12666** [comment]
Thanks, its not very urgent...

**Comment by SoapSeller** [comment]
Hi,

I've encountered the same issue, however, it seems it's even bigger - the last byte of the data of the last nal unit is also missing.

I've removed the "-1" offset in the processing of last nal unit(pes_avc_parser.js, lines 133 and 135) and it seems to fix the problem.
However, I'm not sure if it will not mess with anything else.

Any advice? 

Thanks in advance!

**Comment by birme** [comment]
Great catch! It sounds reasonable. Provide me with a PR and I can have a look. Thank you for the help.

/Jonas

**Comment by birme** [comment]
Thanks @SoapSeller for the PR!
